// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yewbcdiragzvievhqluj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlld2JjZGlyYWd6dmlldmhxbHVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MTc3MzEsImV4cCI6MjA2ODQ5MzczMX0.JZKRuOQZ9fEKSBqoXoL3BgCiq-9mnsRab5DKbdYIirw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});